name: Tests

on: push

jobs:
    # e2e-tests:
    #     runs-on: ubuntu-20.04
    #     steps:
    #         - name: Check out code 🛎
    #           uses: actions/checkout@v2
    #         - name: Run E2E tests 🧪
    #           uses: cypress-io/github-action@v2
    #           with:
    #               install: true
    #               start: npm start
    unit-tests:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  test-script: npm run test:coverage -- --watchAll=false --silent
