name: Tests

on:
    push:
        branches:
            - "**"
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    integration-tests:
        runs-on: ubuntu-20.04
        steps:
            - name: Check out code 🛎
              uses: actions/checkout@v2
            - name: Build docker compose
              run: docker-compose --profile=backend up -d
            - name: docker ps
              run: docker-compose ps
            - name: Run integration tests 🧪
              uses: cypress-io/github-action@v2
              with:
                  install-command: npm install --frozen-lockfile --legacy-peer-deps
                  start: npm start
                  wait-on: "http://localhost:3000"
    unit-tests:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  test-script: npm run test:coverage -- --watchAll=false --silent
